# Generated by Django 3.2.22 on 2024-01-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stomatologiya_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
    ]
