# Generated by Django 3.2.22 on 2024-01-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stomatologiya_app', '0003_auto_20240130_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
