# Generated by Django 3.2.22 on 2024-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stomatologiya_app', '0004_patient_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
